### ISSUE TITLE
Issue with pigpio Initialization on Raspberry Pi 5 Model B

### ISSUE THREAD

**Issue by Flying-Bolt** [joan2937/pigpio#598] opened 2024-01-28 14:16 UTC
Description:

Hello,

I'm trying to use pigpio on my Raspberry Pi 5 Model B, but I'm encountering issues with the initialization. After various attempts and research, I have set the PI_IGNORE_ENV environment variable to 1 to bypass hardware checking, but that hasn't worked.

Hardware Information:

Raspberry Pi 5 Model B
Revision: d04170
Steps to Reproduce the Issue:

Installation of pigpio (sudo apt-get install pigpio)
Compilation of my C++ program with pigpio dependencies
Execution of the program
Error Message:

sql
Copy code
2024-01-28 15:04:40 gpioHardwareRevision: unknown rev code (d04170)
2024-01-28 15:04:40 initCheckPermitted: 
+---------------------------------------------------------+
|Sorry, this system does not appear to be a raspberry pi. |
|aborting.                                                |
+---------------------------------------------------------+
pigpio initialization failed
Additional Information:

I have already attempted to set the PI_IGNORE_ENV environment variable, but it did not improve the situation.
Thank you in advance for your assistance!
![Error](https://github.com/joan2937/pigpio/assets/12726678/b08f77c3-ac21-402a-a61a-f09bc8f4e1cf)

**Comment by Sjohn21** [comment] 2024-02-05 21:17
Duplicate of #589.
Also Refer to #586

**Closed as completed** 2024-02-06 04:54 UTC
